### ISSUE TITLE
Offer option to use system clipboard

### ISSUE THREAD

**Issue by drkwjhnsn** [jpotterm/vscode-simple-vim#21]
Love the extension and its emphasis on "integration" with vscode's native toolset rather than replacement. That being said there doesn't seem to be any integration with the system clipboard.  I'm guessing this may actually be os dependent bug since use of the system clipboard seems like a desirable feature for integration. I'm using a mac and pasting through vim works fine, but yanking has no effect on the system clipboard (i.e., cmd+v won't paste what I yanked, nor will it paste in any other application). Turning off my other extensions has no effect on this behavior.

**Comment by jpotterm** [comment]
I'm glad you're finding this extension useful! Integration with the system clipboard is something I've wanted to have for a while, but unfortunately VSCode doesn't expose the necessary API to extensions to implement it. We need a way to save rich information to the clipboard, not just plain text for two reasons. First, we need to know if it's a linewise yank or not (`p` has different logic for linewise vs regular). Second, we need to save separate text per cursor. When I last looked into it, there was a way to save plaintext to the clipboard, but not richtext. I think VSCode is able to do it internally and that's how it deals with multicursor copy-paste, but it doesn't expose those APIs to extensions.

If you know of a clean way to implement this, I'd be open to it, but otherwise maybe the next step is to submit a feature request to VSCode for exposing the APIs we'd need.

**Comment by drkwjhnsn** [comment]
I can see the issue of trying to maintain current functionality of both `yank` and `put` using the system clipboard, and yeah I'd bet you're right that it would be impossible without updates to the vscode api. However (and this may be particular to me) it seems like "putting" from the clipboard has a lot less practical use cases than "yanking" to it. Personally I like that I can copy text objects easily in vim. Copying a code block with `yi{` is much easier and more precise than dragging the cursor. If you only implement copying to the clipboard, then you can treat it as a side-effect of yanking while continuing to use your own internal register logic.

**Comment by jpotterm** [comment]
It's true, that would be possible, and I'll think about it. But I'm leaning towards not doing that because it seems like it would be of very limited use and broken in many ways. Here are a couple things that wouldn't work as expected:

- `y` then `Cmd+v` with multiple cursors
- `Cmd+c` then `p`

SimpleVim has an `s` operator that you can use to select any motion, so as a workaround instead of `yip` you can do `sip` then `Cmd+c` and avoid using the mouse entirely.

**Comment by drkwjhnsn** [comment]
Guess I missed the `s` operator 😅. Since that takes care of my problem pretty nicely, I'll go ahead and close the issue and PR.

**Comment by jpotterm** [comment]
Great, I'm glad that solves your problem! 😄
