### ISSUE TITLE
r doesn't let me replace a character

### ISSUE THREAD

**Issue by switz** [jpotterm/vscode-simple-vim#28]
So this is by far the best and most simple vim plugin for vscode. It just works, whereas all the other ones are littered with bugs.

The only thing I've ran into is that `r` doesn't let me replace a character beneath the cursor. Perhaps I'm just not using it correctly.

Thanks for a great plugin!

**Comment by jpotterm** [comment]
Yeah, see the README for what `r` does instead with SimpleVim. This is one of the places SimpleVim deviates from Vim, so sorry for the confusion. To replace a character use `cl` instead (also works in Vim).

Thanks for the kind words, and I'm glad you're finding this extension useful!

**Comment by switz** [comment]
Not a major issue -- is it possible for me to restore the traditional functionality somehow?

**Comment by jpotterm** [comment]
Not without modifying the code for this extension. But if that's something you're up for doing either on your local version or on a published fork I'd be happy to give you some guidance about how to do it! It shouldn't be too hard.

**Comment by switz** [comment]
I think I'd be interested -- mind just pointing me towards the relevant lines of code?

**Comment by jpotterm** [comment]
Sure! The higher level vim commands are in the actions folder (https://github.com/jpotterm/vscode-simple-vim/tree/520356a51f75a4b1e55d55717624fdbe8296594d/src/actions). Within that folder they are divided into categories. See the readme for a description of the terminology. You'll see that the readme separates things into the categories: Operators, OperatorRanges, Motions, and Actions and you'll find them in their correspondingly named files in the actions folder.

The first thing you probably want to decide is what to do with the current `r` functionality in SimpleVim. Currently `d` deletes but doesn't yank and `r` is shorthand for delete and yank. You could have `d` delete and yank, or decide you don't need delete and yank together, or find a completely different letter that's not in use currently to delete and yank.

Here is the implementation of the `r` operator:

https://github.com/jpotterm/vscode-simple-vim/blob/520356a51f75a4b1e55d55717624fdbe8296594d/src/actions/operators.ts#L66

and the `rr` (delete and yank current line) and `R` (delete and yank to the end of the line) actions are implemented here:

https://github.com/jpotterm/vscode-simple-vim/blob/520356a51f75a4b1e55d55717624fdbe8296594d/src/actions/actions.ts#L178

Once you've freed up the `r` key, you can implement replace. Single character replace from normal mode would be an action, so you can add that in the actions file. In vim `r` takes an arbitrary character after it, so you'll have to use `parseKeysRegex ` instead of `parseKeysExact`, and you can probably model it after the `t` motion that also takes an arbitrary character:

https://github.com/jpotterm/vscode-simple-vim/blob/520356a51f75a4b1e55d55717624fdbe8296594d/src/actions/motions.ts#L101

From there you can look at the implementation of the other actions and read the VSCode extension documentation to figure out out to replace the current character in the editor.

Hopefully that's helpful. Let me know if you have any questions!
