### ISSUE TITLE
Ctrl+D & Ctrl+U commands don't move the cursor

### ISSUE THREAD

**Issue by adhrinae** [jpotterm/vscode-simple-vim#5]
I like the simplicity of this extension. Great work.

I expected to move the cursor when I press Ctrl+D & Ctrl+U, and also Ctrl+F & Ctrl+B, however, those commands only move the focus of my editor pane and the cursor remains where it has been placed.

Is it an intended behavior? or might be fixable?

**Comment by jpotterm** [comment]
I'm glad you're finding this extension useful, and thanks for the kind words!

This is intentional behavior and I know it differs from Vim so I'm sorry if it trips you up. `Ctrl+u`, `Ctrl+d`, `Ctrl+f`, and `Ctrl+b` scroll the page but don't move the cursor. `H`, `M`, and `L` are for moving the cursor relative to the viewport. So to get the functionality you probably want, you can do `Ctrl+d` until you get where you want and then `M`. It is one more key stroke but I think it provides a clearer separation of concerns between those commands. There are times when you might want to scroll without moving the cursor. One example would be if you just want to look at something below and then continue editing where you are. Another example would be when using multiple cursors you don't want `Ctrl+d` to reposition the cursors because all of them would be collapsed into one.

If you disagree, let me know why. And maybe this warrants mentioning in the "Differences From Vim" section of the README.

**Comment by adhrinae** [comment]
Oh, I didn't read carefully the document and missed some explanations. My bad. I agree with what you concerned about those issue.

I will play around with this extension few more time and let you know if I find something curious.

Going to close this issue and my pull request.
